IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_VENDA]') AND type in (N'U'))
ALTER TABLE [dbo].[TB_VENDA] DROP CONSTRAINT IF EXISTS [FK_TB_VENDA_VENDEDOR]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_VENDA]') AND type in (N'U'))
ALTER TABLE [dbo].[TB_VENDA] DROP CONSTRAINT IF EXISTS [FK_TB_VENDA_LOJA]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_VENDA]') AND type in (N'U'))
ALTER TABLE [dbo].[TB_VENDA] DROP CONSTRAINT IF EXISTS [FK_TB_VENDA_FORMA_PAGAMENTO]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_VENDA]') AND type in (N'U'))
ALTER TABLE [dbo].[TB_VENDA] DROP CONSTRAINT IF EXISTS [FK_TB_VENDA_CLIENTE]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_PRODUTO]') AND type in (N'U'))
ALTER TABLE [dbo].[TB_PRODUTO] DROP CONSTRAINT IF EXISTS [FK_TB_PRODUTO_CATEGORIA_PRODUTO]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_ITEM_VENDA]') AND type in (N'U'))
ALTER TABLE [dbo].[TB_ITEM_VENDA] DROP CONSTRAINT IF EXISTS [FK_TB_VENDA_ITEM_VENDA]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TB_ITEM_VENDA]') AND type in (N'U'))
ALTER TABLE [dbo].[TB_ITEM_VENDA] DROP CONSTRAINT IF EXISTS [FK_TB_ITEM_VENDA_PRODUTO]
GO
/****** Object:  Table [dbo].[TB_VENDEDOR]    Script Date: 11/01/2024 21:08:19 ******/
DROP TABLE IF EXISTS [dbo].[TB_VENDEDOR]
GO
/****** Object:  Table [dbo].[TB_VENDA]    Script Date: 11/01/2024 21:08:19 ******/
DROP TABLE IF EXISTS [dbo].[TB_VENDA]
GO
/****** Object:  Table [dbo].[TB_PRODUTO]    Script Date: 11/01/2024 21:08:19 ******/
DROP TABLE IF EXISTS [dbo].[TB_PRODUTO]
GO
/****** Object:  Table [dbo].[TB_LOJA]    Script Date: 11/01/2024 21:08:19 ******/
DROP TABLE IF EXISTS [dbo].[TB_LOJA]
GO
/****** Object:  Table [dbo].[TB_ITEM_VENDA]    Script Date: 11/01/2024 21:08:19 ******/
DROP TABLE IF EXISTS [dbo].[TB_ITEM_VENDA]
GO
/****** Object:  Table [dbo].[TB_FORMA_PAGAMENTO]    Script Date: 11/01/2024 21:08:19 ******/
DROP TABLE IF EXISTS [dbo].[TB_FORMA_PAGAMENTO]
GO
/****** Object:  Table [dbo].[TB_CLIENTE]    Script Date: 11/01/2024 21:08:19 ******/
DROP TABLE IF EXISTS [dbo].[TB_CLIENTE]
GO
/****** Object:  Table [dbo].[TB_CATEGORIA_PRODUTO]    Script Date: 11/01/2024 21:08:19 ******/
DROP TABLE IF EXISTS [dbo].[TB_CATEGORIA_PRODUTO]
GO

CREATE TABLE dbo.TB_FORMA_PAGAMENTO
(
CODIGO_FORMA_PAGAMENTO	 SMALLINT NOT NULL IDENTITY(1,1)
,DESCRICAO_FORMA_PAGAMENTO VARCHAR(100) NOT NULL
)
GO
ALTER TABLE dbo.TB_FORMA_PAGAMENTO ADD CONSTRAINT [PK_TB_FORMA_PAGAMENTO] PRIMARY KEY (CODIGO_FORMA_PAGAMENTO)
GO

CREATE TABLE dbo.TB_CATEGORIA_PRODUTO
(
CODIGO_CATEGORIA SMALLINT NOT NULL IDENTITY(1,1)
,CATEGORIA_PRODUTO VARCHAR(100) NOT NULL
,SUB_CATEGORIA_PRODUTO  VARCHAR(100)  NOT NULL
)
GO
ALTER TABLE dbo.TB_CATEGORIA_PRODUTO ADD CONSTRAINT [PK_TB_CATEGORIA_PRODUTO] PRIMARY KEY (CODIGO_CATEGORIA)
GO

CREATE TABLE dbo.TB_PRODUTO
(
CODIGO_PRODUTO	 SMALLINT NOT NULL IDENTITY(1,1)
,DESCRICAO_PRODUTO	 VARCHAR(100) NOT NULL
,CODIGO_CATEGORIA SMALLINT NOT NULL
)
GO
ALTER TABLE dbo.TB_PRODUTO ADD CONSTRAINT [PK_TB_PRODUTO] PRIMARY KEY (CODIGO_PRODUTO)
GO
ALTER TABLE dbo.TB_PRODUTO ADD CONSTRAINT [FK_TB_PRODUTO_CATEGORIA_PRODUTO] FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES dbo.TB_CATEGORIA_PRODUTO (CODIGO_CATEGORIA)
GO
CREATE NONCLUSTERED INDEX [IX_01] ON dbo.TB_PRODUTO(CODIGO_CATEGORIA)
GO

CREATE TABLE dbo.TB_CLIENTE
(
CODIGO_CLIENTE INT NOT NULL IDENTITY(1,1)
,NOME_CLIENTE VARCHAR(100) NOT NULL
,DATA_NASCIMENTO DATE NOT NULL
,IDADE_CLIENTE TINYINT NOT NULL
,DESCRICAO_ENDERECO VARCHAR(200) NOT NULL
,NUMERO_ENDERECO SMALLINT NOT NULL
,NOME_CIDADE VARCHAR(100) NOT NULL
,NUMERO_TELEFONE VARCHAR(30) NOT NULL
,EMAIL_CLIENTE VARCHAR(100)  NOT NULL
,OCUPACAO_CLIENTE VARCHAR(100) NOT NULL
)
GO
ALTER TABLE dbo.TB_CLIENTE ADD CONSTRAINT [PK_TB_CLIENTE] PRIMARY KEY (CODIGO_CLIENTE)
GO

CREATE TABLE dbo.TB_VENDEDOR
(
CODIGO_VENDEDOR SMALLINT NOT NULL IDENTITY(1,1)
,NOME_VENDEDOR VARCHAR(100) NOT NULL
)
GO
ALTER TABLE dbo.TB_VENDEDOR ADD CONSTRAINT [PK_CODIGO_VENDEDOR] PRIMARY KEY (CODIGO_VENDEDOR)
GO

CREATE TABLE dbo.TB_LOJA
(
CODIGO_LOJA	 SMALLINT NOT NULL IDENTITY(1,1)
,NOME_LOJA	 VARCHAR(100) NOT NULL
,LOCALIDADE_LOJA	 VARCHAR(100) NOT NULL
,TIPO_LOJA VARCHAR(100) NOT NULL
)
GO
ALTER TABLE dbo.TB_LOJA ADD CONSTRAINT [PK_TB_LOJA] PRIMARY KEY (CODIGO_LOJA)
GO

CREATE TABLE dbo.TB_VENDA
(
CODIGO_VENDA INT NOT NULL IDENTITY(1,1)	
,DATA_VENDA	DATETIME NOT NULL 
,CODIGO_CLIENTE	INT
,CODIGO_VENDEDOR	SMALLINT
,CODIGO_LOJA	SMALLINT
,VALOR_FINAL DECIMAL(18,2)	
,FORMA_PAGAMENTO	SMALLINT
,TIPO_PAGAMENTO VARCHAR(100) NOT NULL
)
GO

ALTER TABLE dbo.TB_VENDA ADD CONSTRAINT [PK_TB_VENDA] PRIMARY KEY (CODIGO_VENDA)
GO
ALTER TABLE dbo.TB_VENDA ADD CONSTRAINT [FK_TB_VENDA_CLIENTE] FOREIGN KEY (CODIGO_CLIENTE) REFERENCES dbo.TB_CLIENTE (CODIGO_CLIENTE)
GO
ALTER TABLE dbo.TB_VENDA ADD CONSTRAINT [FK_TB_VENDA_FORMA_PAGAMENTO] FOREIGN KEY (FORMA_PAGAMENTO) REFERENCES dbo.TB_FORMA_PAGAMENTO (CODIGO_FORMA_PAGAMENTO)
GO
ALTER TABLE dbo.TB_VENDA ADD CONSTRAINT [FK_TB_VENDA_VENDEDOR] FOREIGN KEY (CODIGO_VENDEDOR) REFERENCES dbo.TB_VENDEDOR (CODIGO_VENDEDOR)
GO
ALTER TABLE dbo.TB_VENDA ADD CONSTRAINT [FK_TB_VENDA_LOJA] FOREIGN KEY (CODIGO_LOJA) REFERENCES dbo.TB_LOJA (CODIGO_LOJA)
GO

CREATE NONCLUSTERED INDEX [IX_01] ON dbo.TB_VENDA(CODIGO_CLIENTE)
GO
CREATE NONCLUSTERED INDEX [IX_02] ON dbo.TB_VENDA(FORMA_PAGAMENTO)
GO
CREATE NONCLUSTERED INDEX [IX_03] ON dbo.TB_VENDA(CODIGO_VENDEDOR)
GO
CREATE NONCLUSTERED INDEX [IX_04] ON dbo.TB_VENDA(CODIGO_LOJA)
GO


CREATE TABLE dbo.TB_ITEM_VENDA
(
CODIGO_VENDA INT NOT NULL 
,CODIGO_PRODUTO	SMALLINT NOT NULL 
,VALOR_UNITARIO DECIMAL(18,2)	
,QUANTIDADE	SMALLINT
,VALOR_FINAL DECIMAL(18,2)
)
GO

ALTER TABLE dbo.TB_ITEM_VENDA ADD CONSTRAINT [PK_TB_ITEM_VENDA] PRIMARY KEY (CODIGO_VENDA,CODIGO_PRODUTO)
GO
ALTER TABLE dbo.TB_ITEM_VENDA ADD CONSTRAINT [FK_TB_VENDA_ITEM_VENDA] FOREIGN KEY (CODIGO_VENDA) REFERENCES dbo.TB_VENDA (CODIGO_VENDA)
GO
ALTER TABLE dbo.TB_ITEM_VENDA ADD CONSTRAINT [FK_TB_ITEM_VENDA_PRODUTO] FOREIGN KEY (CODIGO_PRODUTO) REFERENCES dbo.TB_PRODUTO (CODIGO_PRODUTO)
GO

CREATE NONCLUSTERED INDEX [IX_01] ON dbo.TB_ITEM_VENDA(CODIGO_VENDA)
GO
CREATE NONCLUSTERED INDEX [IX_02] ON dbo.TB_ITEM_VENDA(CODIGO_PRODUTO)
GO