
INSERT INTO dbo.TB_FORMA_PAGAMENTO (DESCRICAO_FORMA_PAGAMENTO) VALUES ('CARTÃO CRÉDITO');
INSERT INTO dbo.TB_FORMA_PAGAMENTO (DESCRICAO_FORMA_PAGAMENTO) VALUES ('CARTÃO DÉBITO');
INSERT INTO dbo.TB_FORMA_PAGAMENTO (DESCRICAO_FORMA_PAGAMENTO) VALUES ('BOLETO');
INSERT INTO dbo.TB_FORMA_PAGAMENTO (DESCRICAO_FORMA_PAGAMENTO) VALUES ('PIX');

INSERT INTO dbo.TB_CATEGORIA_PRODUTO (DECRICAO_CATEGORIA) VALUES ('CELULAR');
INSERT INTO dbo.TB_CATEGORIA_PRODUTO (DECRICAO_CATEGORIA) VALUES ('ELETRODOMÉSTICO');
INSERT INTO dbo.TB_CATEGORIA_PRODUTO (DECRICAO_CATEGORIA) VALUES ('ACESSÓRIO');
INSERT INTO dbo.TB_CATEGORIA_PRODUTO (DECRICAO_CATEGORIA) VALUES ('COMPUTADOR');
INSERT INTO dbo.TB_CATEGORIA_PRODUTO (DECRICAO_CATEGORIA) VALUES ('VESTUÁRIO');


INSERT INTO dbo.TB_PRODUTO (DESCRICAO_PRODUTO,CODIGO_CATEGORIA) VALUES ('IPHONE 11',1);
INSERT INTO dbo.TB_PRODUTO (DESCRICAO_PRODUTO,CODIGO_CATEGORIA) VALUES ('GELADEIRA FROSTFREE BRASTEMP',2);
INSERT INTO dbo.TB_PRODUTO (DESCRICAO_PRODUTO,CODIGO_CATEGORIA) VALUES ('FOGÃO 5 BOCAS BRASTEMP',2);
INSERT INTO dbo.TB_PRODUTO (DESCRICAO_PRODUTO,CODIGO_CATEGORIA) VALUES ('PENDRIVE SCANDISK CRUZER BLADE 128 GB',3);
INSERT INTO dbo.TB_PRODUTO (DESCRICAO_PRODUTO,CODIGO_CATEGORIA) VALUES ('NOTEBOOK MACBOOK PRO 14 M2',4);
INSERT INTO dbo.TB_PRODUTO (DESCRICAO_PRODUTO,CODIGO_CATEGORIA) VALUES ('CAMISA FLUMINENSE 23/23',5);


INSERT INTO dbo.TB_CLIENTE (NOME_CLIENTE) VALUES ('CRISTOVÃO COLOMBO');
INSERT INTO dbo.TB_CLIENTE (NOME_CLIENTE) VALUES ('PEDRO ALVARES CABRAL');
INSERT INTO dbo.TB_CLIENTE (NOME_CLIENTE) VALUES ('MACHADO DE ASSIS');
INSERT INTO dbo.TB_CLIENTE (NOME_CLIENTE) VALUES ('CHICO BUARQUE DE HOLANDA');
INSERT INTO dbo.TB_CLIENTE (NOME_CLIENTE) VALUES ('MAURICIO DE SOUZA');


INSERT INTO dbo.TB_VENDEDOR (NOME_VENDEDOR) VALUES ('WWW');
INSERT INTO dbo.TB_VENDEDOR (NOME_VENDEDOR) VALUES ('JOSÉ ROBERTO');
INSERT INTO dbo.TB_VENDEDOR (NOME_VENDEDOR) VALUES ('MARIA ANTONIETA');
INSERT INTO dbo.TB_VENDEDOR (NOME_VENDEDOR) VALUES ('CLARICE LISPECTOR');
INSERT INTO dbo.TB_VENDEDOR (NOME_VENDEDOR) VALUES ('ALEXANDRE PIRES');
INSERT INTO dbo.TB_VENDEDOR (NOME_VENDEDOR) VALUES ('ZEZÉ DE CAMARGO');


INSERT INTO dbo.TB_LOJA (NOME_LOJA,LOCALIDADE_LOJA,TIPO_LOJA) VALUES ('E-COMMERCE','WWW','VIRTUAL');
INSERT INTO dbo.TB_LOJA (NOME_LOJA,LOCALIDADE_LOJA,TIPO_LOJA) VALUES ('LOJA A','MT','FÍSICA');
INSERT INTO dbo.TB_LOJA (NOME_LOJA,LOCALIDADE_LOJA,TIPO_LOJA) VALUES ('LOJA B','RJ','FÍSICA');
INSERT INTO dbo.TB_LOJA (NOME_LOJA,LOCALIDADE_LOJA,TIPO_LOJA) VALUES ('LOJA C','CE','FÍSICA');


INSERT INTO dbo.TB_VENDA (DATA_VENDA,CODIGO_CLIENTE,CODIGO_VENDEDOR,CODIGO_LOJA,VALOR_FINAL,FORMA_PAGAMENTO,TIPO_PAGAMENTO) VALUES ('2023-07-10',1,2,2,'12834.56',2,'A VISTA');
INSERT INTO dbo.TB_VENDA (DATA_VENDA,CODIGO_CLIENTE,CODIGO_VENDEDOR,CODIGO_LOJA,VALOR_FINAL,FORMA_PAGAMENTO,TIPO_PAGAMENTO) VALUES ('2023-07-10',4,3,2,'5873.5',4,'A VISTA');
INSERT INTO dbo.TB_VENDA (DATA_VENDA,CODIGO_CLIENTE,CODIGO_VENDEDOR,CODIGO_LOJA,VALOR_FINAL,FORMA_PAGAMENTO,TIPO_PAGAMENTO) VALUES ('2023-07-11',3,1,1,'20769.02',1,'PARCELADO');
INSERT INTO dbo.TB_VENDA (DATA_VENDA,CODIGO_CLIENTE,CODIGO_VENDEDOR,CODIGO_LOJA,VALOR_FINAL,FORMA_PAGAMENTO,TIPO_PAGAMENTO) VALUES ('2023-07-11',1,4,4,'18232.25',2,'A VISTA');
INSERT INTO dbo.TB_VENDA (DATA_VENDA,CODIGO_CLIENTE,CODIGO_VENDEDOR,CODIGO_LOJA,VALOR_FINAL,FORMA_PAGAMENTO,TIPO_PAGAMENTO) VALUES ('2023-07-12',5,6,3,'18407.93',1,'PARCELADO');
INSERT INTO dbo.TB_VENDA (DATA_VENDA,CODIGO_CLIENTE,CODIGO_VENDEDOR,CODIGO_LOJA,VALOR_FINAL,FORMA_PAGAMENTO,TIPO_PAGAMENTO) VALUES ('2023-07-12',3,1,1,'38602.18',3,'A VISTA');
INSERT INTO dbo.TB_VENDA (DATA_VENDA,CODIGO_CLIENTE,CODIGO_VENDEDOR,CODIGO_LOJA,VALOR_FINAL,FORMA_PAGAMENTO,TIPO_PAGAMENTO) VALUES ('2023-07-13',4,6,3,'6778.95',1,'PARCELADO');
INSERT INTO dbo.TB_VENDA (DATA_VENDA,CODIGO_CLIENTE,CODIGO_VENDEDOR,CODIGO_LOJA,VALOR_FINAL,FORMA_PAGAMENTO,TIPO_PAGAMENTO) VALUES ('2023-07-13',2,5,4,'15766.85',4,'A VISTA');



INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (1,1,'2789.9',4,'11159.6');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (1,4,'64.9',10,'649');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (1,6,'256.49',4,'1025.96');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (2,2,'3989.05',1,'3989.05');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (2,3,'1884.45',1,'1884.45');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (3,5,'16266.99',1,'16266.99');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (3,6,'256.49',2,'512.98');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (3,2,'3989.05',1,'3989.05');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (4,1,'2789.9',3,'8369.7');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (4,2,'3989.05',2,'7978.1');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (4,3,'1884.45',1,'1884.45');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (5,5,'16266.99',1,'16266.99');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (5,6,'256.49',1,'256.49');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (5,3,'1884.45',1,'1884.45');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (6,4,'64.9',3,'194.7');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (6,3,'1884.45',1,'1884.45');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (6,5,'16266.99',2,'32533.98');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (6,2,'3989.05',1,'3989.05');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (7,1,'2789.9',1,'2789.9');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (7,2,'3989.05',1,'3989.05');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (8,1,'2789.9',2,'5579.8');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (8,2,'3989.05',2,'7978.1');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (8,3,'1884.45',1,'1884.45');
INSERT INTO dbo.TB_ITEM_VENDA (CODIGO_VENDA,CODIGO_PRODUTO,VALOR_UNITARIO,QUANTIDADE,VALOR_FINAL) VALUES (8,4,'64.9',5,'324.5');
